In [8]:
a = 1
b = 10
#count = 0
while a<b:
    print(a)
    a += 1
    if a > 5:
        continue
    print("loop iteration completed")
print("completed")

1
loop iteration completed
2
loop iteration completed
3
loop iteration completed
4
loop iteration completed
5
6
7
8
9
completed


In [5]:
string1 ="Hello Python"
string2 ="hello"

#invlude 
print( string2.upper() in string1.upper()) #membership 

True


In [9]:
list1 = [1,3,2,3,"45"]
list1

[1, 3, 2, 3, '45']

In [18]:
for i in range(0,len(list1)): #iteration
    print(f" at index \t{i} \n value is {list1[i]}\n")

 at index 	0 
 value is 1

 at index 	1 
 value is 3

 at index 	2 
 value is 2

 at index 	3 
 value is 3

 at index 	4 
 value is 45



In [11]:
len(list1)

5

In [24]:
# 12 20 
# 30 40

row1 = [ 10, 20 ]
row2 = [ 30, 40 ]

matrix = [row1, row2]
matrix, len(matrix)

([[10, 20], [30, 40]], 2)

In [25]:
matrix[0][0]

10

In [45]:
# print value and id 
def showDetails(val):
    print (f"value is {val} \n id is {id(val)}\n ")


In [46]:
showDetails(list1)

value is [1, 3, 2, 3, '45'] 
 id is 1511342386048
 


In [52]:
# Question
# create a 3*3 matrix with a variable name a and store in a variable a and make it copy of this variable in b like b=a then m odify in values in b and then print its value in ide 

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = a.copy()

b[0, 0] = 10
print(b)



[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [53]:
listA = [2, 4, 6, [1,3]]
listB = listA
showDetails(listA,listB)
listB[1] = 44
listB[3][0] = 55

showDetails(listA,listB)

TypeError: showDetails() takes 1 positional argument but 2 were given

In [59]:
#write a function that calculate a force , mass*accelrataion 
def calculate_force(mass, acceleration):
    #formula 
    force = mass * acceleration
    return force

mass = float(input("Enter mass : "))
acceleration = float(input("Enter acceleration : "))

# Calculating force
force = calculate_force(mass, acceleration)

# Output
print(f"Force {force} ")


Enter mass :  10
Enter acceleration :  10


Force 100.0 


# 2/09/2024 

#### Functions

In [9]:
def functionname(inputArguments,Arg2):
    #Code 
    pass

In [26]:
import testfile

ModuleNotFoundError: No module named 'testfile'

In [27]:
math.pi

NameError: name 'math' is not defined

In [30]:
# Write a function add two variables

def addnumbers(a, b):
    return a + b
result = addnumbers(5, 10)
print(" sum :", result)

 sum : 15


In [29]:
def addnumbers(a, b, c, d, e):
    return a + b + c + d + e
result = addnumbers(5, 10, 1, 2 ,3)
print(" sum :", result)

 sum : 21


In [10]:
def greet (name, message):
    print(f"Hi {name}{message}")

name = "Lucky"
message =" how are you"
greet (name, message)

Hi Lucky how are you


# 09/09/2024

### Unit-2  Scope 

In [4]:
# Scope 
x = 10 
def outer_function():
    x = 20 #Enclosing Variable
    def inner_function():
        x = 30
        print(x)
    inner_function()
    print(x)

outer_function()
print(x)

30
20
10


 #### write a function to multiply 3 number and return its result 

In [6]:
number =[1,2,3]
x = list(map(lambda x: x*2 , number))

In [8]:
x

[2, 4, 6]

In [9]:
def multiply(x):
    for i in x:
        return x*2

In [10]:
import numpy as np
num = np.array([1,2,3])
multiply(num)

array([2, 4, 6])