In [8]:
a = 1
b = 10
#count = 0
while a<b:
    print(a)
    a += 1
    if a > 5:
        continue
    print("loop iteration completed")
print("completed")

1
loop iteration completed
2
loop iteration completed
3
loop iteration completed
4
loop iteration completed
5
6
7
8
9
completed


In [5]:
string1 ="Hello Python"
string2 ="hello"

print( string2.upper() in string1.upper()) #membership 

True


In [9]:
list1 = [1,3,2,3,"45"]
list1

[1, 3, 2, 3, '45']

In [18]:
for i in range(0,len(list1)): #iteration
    print(f" at index \t{i} \n value is {list1[i]}\n")

 at index 	0 
 value is 1

 at index 	1 
 value is 3

 at index 	2 
 value is 2

 at index 	3 
 value is 3

 at index 	4 
 value is 45



In [11]:
len(list1)

5

In [24]:


row1 = [ 10, 20 ]
row2 = [ 30, 40 ]

matrix = [row1, row2]
matrix, len(matrix)

([[10, 20], [30, 40]], 2)

In [25]:
matrix[0][0]

10

In [45]:

def showDetails(val):
    print (f"value is {val} \n id is {id(val)}\n ")


In [46]:
showDetails(list1)

value is [1, 3, 2, 3, '45'] 
 id is 1511342386048
 


In [52]:
# Question
# create a 3*3 matrix with a variable name a and store in a variable a and make it copy of this variable in b like b=a then m odify in values in b and then print its value in ide 

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = a.copy()

b[0, 0] = 10
print(b)



[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [53]:
listA = [2, 4, 6, [1,3]]
listB = listA
showDetails(listA,listB)
listB[1] = 44
listB[3][0] = 55

showDetails(listA,listB)

TypeError: showDetails() takes 1 positional argument but 2 were given

In [ ]:
#write a function that calculate a force , mass*accelrataion 
def calculate_force(mass, acceleration):
    
    force = mass * acceleration
    return force

mass = float(input("Enter mass : "))
acceleration = float(input("Enter acceleration : "))


force = calculate_force(mass, acceleration)


print(f"Force {force} ")
